name: Auto-publish
on:
  pull_request: {}
  push:
    paths:
      - index.bs
    branches: [main]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          VALIDATE_LINKS: false
          BUILD_FAIL_ON: warning
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2021Jun/0011.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_BUILD_OVERRIDE: |
            TR: https://www.w3.org/TR/webnn/
            status: CRD
      - name: WebNN - Lint Bikeshed Source and Generated HTML
        id: webnn-lint
        shell: bash
        env:
          BIKESHED_SOURCE: "index.bs"
          GENERATED_HTML: "index.bs.built.html"
        run: |
          echo "::group::Install Lint Tool Dependencies"
          cd tools
          npm install
          cd ..
          echo "::endgroup::"
          echo "::group::Generate Static HTML"
          bikeshed --die-on=warning spec $BIKESHED_SOURCE $GENERATED_HTML
          echo "::endgroup::"
          echo "::group::Run Lint Tool"
          node tools/lint.mjs --verbose --bikeshed $BIKESHED_SOURCE --html $GENERATED_HTML
          echo "::endgroup::"
